name: firestore_ref
description: Firestore reference/document typed acccess helpers. You can write organized safe code by this.
version: 0.8.12+2
homepage: https://github.com/mono0926/flutter_firestore_ref
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  disposable_provider: ^2.2.0
  firebase: ^7.3.0
  json_annotation: ^3.0.1
  simple_logger: ^1.7.0
  meta: ^1.1.8
  quiver: ^2.1.3
  rxdart: ^0.24.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter: